apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: prod
  name: flask-deployment
  labels:
    app: flask
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask
  template:
    metadata:
      labels:
        app: flask
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: '5000'
    spec:
      containers:
      - name: flask
        image: docker.io/chanprak/flask-sample-one:prod
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        env:
          - name: JAEGER_SERVICE_NAME
            value: flask
          - name: JAEGER_AGENT_HOST
            valueFrom:
              fieldRef:
                fieldPath: status.hostIP
          - name: JAEGER_AGENT_PORT
            value: "6831"
---
apiVersion: v1
kind: Service
metadata:
  namespace: prod
  name: flask
  labels:
    app: flask
spec:
  ports:
  - port: 80
    targetPort: 5000
    protocol: TCP
  selector:
    app: flask
  type: LoadBalancer