# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: products.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import base_pb2 as base__pb2
import reviews_pb2 as reviews__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='products.proto',
  package='com.declayer.store',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0eproducts.proto\x12\x12\x63om.declayer.store\x1a\nbase.proto\x1a\rreviews.proto\"\x85\x01\n\x07Product\x12\x1d\n\x02id\x18\x01 \x01(\x0b\x32\x11.shared.ProductId\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12\x13\n\x0b\x63\x61tegory_id\x18\x04 \x01(\t\x12\x10\n\x08keywords\x18\x05 \x03(\t\x12\x11\n\tphotoUrls\x18\x06 \x03(\t\"l\n\x0fReviewedProduct\x12,\n\x07product\x18\x01 \x01(\x0b\x32\x1b.com.declayer.store.Product\x12+\n\x07reviews\x18\x02 \x03(\x0b\x32\x1a.com.declayer.store.Review2\xd3\x01\n\x08Products\x12\x46\n\nGetProduct\x12\x11.shared.ProductId\x1a#.com.declayer.store.ReviewedProduct\"\x00\x12>\n\x0cListProducts\x12\r.shared.Limit\x1a\x1b.com.declayer.store.Product\"\x00\x30\x01\x12?\n\x0bSaveProduct\x12\x1b.com.declayer.store.Product\x1a\x11.shared.ProductId\"\x00\x62\x06proto3')
  ,
  dependencies=[base__pb2.DESCRIPTOR,reviews__pb2.DESCRIPTOR,])




_PRODUCT = _descriptor.Descriptor(
  name='Product',
  full_name='com.declayer.store.Product',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='com.declayer.store.Product.id', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='com.declayer.store.Product.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='description', full_name='com.declayer.store.Product.description', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='category_id', full_name='com.declayer.store.Product.category_id', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='keywords', full_name='com.declayer.store.Product.keywords', index=4,
      number=5, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='photoUrls', full_name='com.declayer.store.Product.photoUrls', index=5,
      number=6, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=66,
  serialized_end=199,
)


_REVIEWEDPRODUCT = _descriptor.Descriptor(
  name='ReviewedProduct',
  full_name='com.declayer.store.ReviewedProduct',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='product', full_name='com.declayer.store.ReviewedProduct.product', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='reviews', full_name='com.declayer.store.ReviewedProduct.reviews', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=201,
  serialized_end=309,
)

_PRODUCT.fields_by_name['id'].message_type = base__pb2._PRODUCTID
_REVIEWEDPRODUCT.fields_by_name['product'].message_type = _PRODUCT
_REVIEWEDPRODUCT.fields_by_name['reviews'].message_type = reviews__pb2._REVIEW
DESCRIPTOR.message_types_by_name['Product'] = _PRODUCT
DESCRIPTOR.message_types_by_name['ReviewedProduct'] = _REVIEWEDPRODUCT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Product = _reflection.GeneratedProtocolMessageType('Product', (_message.Message,), dict(
  DESCRIPTOR = _PRODUCT,
  __module__ = 'products_pb2'
  # @@protoc_insertion_point(class_scope:com.declayer.store.Product)
  ))
_sym_db.RegisterMessage(Product)

ReviewedProduct = _reflection.GeneratedProtocolMessageType('ReviewedProduct', (_message.Message,), dict(
  DESCRIPTOR = _REVIEWEDPRODUCT,
  __module__ = 'products_pb2'
  # @@protoc_insertion_point(class_scope:com.declayer.store.ReviewedProduct)
  ))
_sym_db.RegisterMessage(ReviewedProduct)



_PRODUCTS = _descriptor.ServiceDescriptor(
  name='Products',
  full_name='com.declayer.store.Products',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=312,
  serialized_end=523,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetProduct',
    full_name='com.declayer.store.Products.GetProduct',
    index=0,
    containing_service=None,
    input_type=base__pb2._PRODUCTID,
    output_type=_REVIEWEDPRODUCT,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='ListProducts',
    full_name='com.declayer.store.Products.ListProducts',
    index=1,
    containing_service=None,
    input_type=base__pb2._LIMIT,
    output_type=_PRODUCT,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='SaveProduct',
    full_name='com.declayer.store.Products.SaveProduct',
    index=2,
    containing_service=None,
    input_type=_PRODUCT,
    output_type=base__pb2._PRODUCTID,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_PRODUCTS)

DESCRIPTOR.services_by_name['Products'] = _PRODUCTS

# @@protoc_insertion_point(module_scope)
