# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import base_pb2 as base__pb2
import products_pb2 as products__pb2


class ProductsStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.GetProduct = channel.unary_unary(
        '/com.declayer.store.Products/GetProduct',
        request_serializer=base__pb2.ProductId.SerializeToString,
        response_deserializer=products__pb2.ReviewedProduct.FromString,
        )
    self.ListProducts = channel.unary_stream(
        '/com.declayer.store.Products/ListProducts',
        request_serializer=base__pb2.Limit.SerializeToString,
        response_deserializer=products__pb2.Product.FromString,
        )
    self.SaveProduct = channel.unary_unary(
        '/com.declayer.store.Products/SaveProduct',
        request_serializer=products__pb2.Product.SerializeToString,
        response_deserializer=base__pb2.ProductId.FromString,
        )


class ProductsServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def GetProduct(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ListProducts(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SaveProduct(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_ProductsServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'GetProduct': grpc.unary_unary_rpc_method_handler(
          servicer.GetProduct,
          request_deserializer=base__pb2.ProductId.FromString,
          response_serializer=products__pb2.ReviewedProduct.SerializeToString,
      ),
      'ListProducts': grpc.unary_stream_rpc_method_handler(
          servicer.ListProducts,
          request_deserializer=base__pb2.Limit.FromString,
          response_serializer=products__pb2.Product.SerializeToString,
      ),
      'SaveProduct': grpc.unary_unary_rpc_method_handler(
          servicer.SaveProduct,
          request_deserializer=products__pb2.Product.FromString,
          response_serializer=base__pb2.ProductId.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'com.declayer.store.Products', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
