# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: reviews.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import base_pb2 as base__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='reviews.proto',
  package='com.declayer.store',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\rreviews.proto\x12\x12\x63om.declayer.store\x1a\nbase.proto\"T\n\x0eReviewsRequest\x12$\n\tproductId\x18\x01 \x01(\x0b\x32\x11.shared.ProductId\x12\x1c\n\x05limit\x18\x02 \x01(\x0b\x32\r.shared.Limit\"\x16\n\x08ReviewId\x12\n\n\x02id\x18\x01 \x01(\x05\"\xdc\x01\n\x06Review\x12(\n\x02id\x18\x01 \x01(\x0b\x32\x1c.com.declayer.store.ReviewId\x12$\n\tproductId\x18\x02 \x01(\x0b\x32\x11.shared.ProductId\x12\x1e\n\x06userId\x18\x03 \x01(\x0b\x32\x0e.shared.UserId\x12\x17\n\x0freviewTimestamp\x18\x04 \x01(\x03\x12\x1c\n\x14lastUpdatedTimestamp\x18\x05 \x01(\x03\x12\x12\n\nreviewText\x18\x06 \x01(\t\x12\x17\n\x0freviewImageUrls\x18\x07 \x03(\t2\xa5\x01\n\x07Reviews\x12P\n\nGetReviews\x12\".com.declayer.store.ReviewsRequest\x1a\x1a.com.declayer.store.Review\"\x00\x30\x01\x12H\n\nSaveReview\x12\x1a.com.declayer.store.Review\x1a\x1c.com.declayer.store.ReviewId\"\x00\x62\x06proto3')
  ,
  dependencies=[base__pb2.DESCRIPTOR,])




_REVIEWSREQUEST = _descriptor.Descriptor(
  name='ReviewsRequest',
  full_name='com.declayer.store.ReviewsRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='productId', full_name='com.declayer.store.ReviewsRequest.productId', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='limit', full_name='com.declayer.store.ReviewsRequest.limit', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=49,
  serialized_end=133,
)


_REVIEWID = _descriptor.Descriptor(
  name='ReviewId',
  full_name='com.declayer.store.ReviewId',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='com.declayer.store.ReviewId.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=135,
  serialized_end=157,
)


_REVIEW = _descriptor.Descriptor(
  name='Review',
  full_name='com.declayer.store.Review',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='com.declayer.store.Review.id', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='productId', full_name='com.declayer.store.Review.productId', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='userId', full_name='com.declayer.store.Review.userId', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='reviewTimestamp', full_name='com.declayer.store.Review.reviewTimestamp', index=3,
      number=4, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='lastUpdatedTimestamp', full_name='com.declayer.store.Review.lastUpdatedTimestamp', index=4,
      number=5, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='reviewText', full_name='com.declayer.store.Review.reviewText', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='reviewImageUrls', full_name='com.declayer.store.Review.reviewImageUrls', index=6,
      number=7, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=160,
  serialized_end=380,
)

_REVIEWSREQUEST.fields_by_name['productId'].message_type = base__pb2._PRODUCTID
_REVIEWSREQUEST.fields_by_name['limit'].message_type = base__pb2._LIMIT
_REVIEW.fields_by_name['id'].message_type = _REVIEWID
_REVIEW.fields_by_name['productId'].message_type = base__pb2._PRODUCTID
_REVIEW.fields_by_name['userId'].message_type = base__pb2._USERID
DESCRIPTOR.message_types_by_name['ReviewsRequest'] = _REVIEWSREQUEST
DESCRIPTOR.message_types_by_name['ReviewId'] = _REVIEWID
DESCRIPTOR.message_types_by_name['Review'] = _REVIEW
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ReviewsRequest = _reflection.GeneratedProtocolMessageType('ReviewsRequest', (_message.Message,), dict(
  DESCRIPTOR = _REVIEWSREQUEST,
  __module__ = 'reviews_pb2'
  # @@protoc_insertion_point(class_scope:com.declayer.store.ReviewsRequest)
  ))
_sym_db.RegisterMessage(ReviewsRequest)

ReviewId = _reflection.GeneratedProtocolMessageType('ReviewId', (_message.Message,), dict(
  DESCRIPTOR = _REVIEWID,
  __module__ = 'reviews_pb2'
  # @@protoc_insertion_point(class_scope:com.declayer.store.ReviewId)
  ))
_sym_db.RegisterMessage(ReviewId)

Review = _reflection.GeneratedProtocolMessageType('Review', (_message.Message,), dict(
  DESCRIPTOR = _REVIEW,
  __module__ = 'reviews_pb2'
  # @@protoc_insertion_point(class_scope:com.declayer.store.Review)
  ))
_sym_db.RegisterMessage(Review)



_REVIEWS = _descriptor.ServiceDescriptor(
  name='Reviews',
  full_name='com.declayer.store.Reviews',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=383,
  serialized_end=548,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetReviews',
    full_name='com.declayer.store.Reviews.GetReviews',
    index=0,
    containing_service=None,
    input_type=_REVIEWSREQUEST,
    output_type=_REVIEW,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='SaveReview',
    full_name='com.declayer.store.Reviews.SaveReview',
    index=1,
    containing_service=None,
    input_type=_REVIEW,
    output_type=_REVIEWID,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_REVIEWS)

DESCRIPTOR.services_by_name['Reviews'] = _REVIEWS

# @@protoc_insertion_point(module_scope)
