# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import reviews_pb2 as reviews__pb2


class ReviewsStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.GetReviews = channel.unary_stream(
        '/com.declayer.store.Reviews/GetReviews',
        request_serializer=reviews__pb2.ReviewsRequest.SerializeToString,
        response_deserializer=reviews__pb2.Review.FromString,
        )
    self.SaveReview = channel.unary_unary(
        '/com.declayer.store.Reviews/SaveReview',
        request_serializer=reviews__pb2.Review.SerializeToString,
        response_deserializer=reviews__pb2.ReviewId.FromString,
        )


class ReviewsServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def GetReviews(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SaveReview(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_ReviewsServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'GetReviews': grpc.unary_stream_rpc_method_handler(
          servicer.GetReviews,
          request_deserializer=reviews__pb2.ReviewsRequest.FromString,
          response_serializer=reviews__pb2.Review.SerializeToString,
      ),
      'SaveReview': grpc.unary_unary_rpc_method_handler(
          servicer.SaveReview,
          request_deserializer=reviews__pb2.Review.FromString,
          response_serializer=reviews__pb2.ReviewId.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'com.declayer.store.Reviews', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
