# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: similar.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import base_pb2 as base__pb2
import reviews_pb2 as reviews__pb2
import products_pb2 as products__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='similar.proto',
  package='com.declayer.store',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\rsimilar.proto\x12\x12\x63om.declayer.store\x1a\nbase.proto\x1a\rreviews.proto\x1a\x0eproducts.proto\"[\n\x15SimilarProductRequest\x12$\n\tproductId\x18\x01 \x01(\x0b\x32\x11.shared.ProductId\x12\x1c\n\x05limit\x18\x02 \x01(\x0b\x32\r.shared.Limit2{\n\x0fSimilarProducts\x12h\n\x12GetSimilarProducts\x12).com.declayer.store.SimilarProductRequest\x1a#.com.declayer.store.ReviewedProduct\"\x00\x30\x01\x62\x06proto3')
  ,
  dependencies=[base__pb2.DESCRIPTOR,reviews__pb2.DESCRIPTOR,products__pb2.DESCRIPTOR,])




_SIMILARPRODUCTREQUEST = _descriptor.Descriptor(
  name='SimilarProductRequest',
  full_name='com.declayer.store.SimilarProductRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='productId', full_name='com.declayer.store.SimilarProductRequest.productId', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='limit', full_name='com.declayer.store.SimilarProductRequest.limit', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=80,
  serialized_end=171,
)

_SIMILARPRODUCTREQUEST.fields_by_name['productId'].message_type = base__pb2._PRODUCTID
_SIMILARPRODUCTREQUEST.fields_by_name['limit'].message_type = base__pb2._LIMIT
DESCRIPTOR.message_types_by_name['SimilarProductRequest'] = _SIMILARPRODUCTREQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SimilarProductRequest = _reflection.GeneratedProtocolMessageType('SimilarProductRequest', (_message.Message,), dict(
  DESCRIPTOR = _SIMILARPRODUCTREQUEST,
  __module__ = 'similar_pb2'
  # @@protoc_insertion_point(class_scope:com.declayer.store.SimilarProductRequest)
  ))
_sym_db.RegisterMessage(SimilarProductRequest)



_SIMILARPRODUCTS = _descriptor.ServiceDescriptor(
  name='SimilarProducts',
  full_name='com.declayer.store.SimilarProducts',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=173,
  serialized_end=296,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetSimilarProducts',
    full_name='com.declayer.store.SimilarProducts.GetSimilarProducts',
    index=0,
    containing_service=None,
    input_type=_SIMILARPRODUCTREQUEST,
    output_type=products__pb2._REVIEWEDPRODUCT,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_SIMILARPRODUCTS)

DESCRIPTOR.services_by_name['SimilarProducts'] = _SIMILARPRODUCTS

# @@protoc_insertion_point(module_scope)
