# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import products_pb2 as products__pb2
import similar_pb2 as similar__pb2


class SimilarProductsStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.GetSimilarProducts = channel.unary_stream(
        '/com.declayer.store.SimilarProducts/GetSimilarProducts',
        request_serializer=similar__pb2.SimilarProductRequest.SerializeToString,
        response_deserializer=products__pb2.ReviewedProduct.FromString,
        )


class SimilarProductsServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def GetSimilarProducts(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_SimilarProductsServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'GetSimilarProducts': grpc.unary_stream_rpc_method_handler(
          servicer.GetSimilarProducts,
          request_deserializer=similar__pb2.SimilarProductRequest.FromString,
          response_serializer=products__pb2.ReviewedProduct.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'com.declayer.store.SimilarProducts', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
